www.infer.discordwell.com {
	redir https://infer.discordwell.com{uri} permanent
}

infer.discordwell.com {
	header {
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Referrer-Policy "strict-origin-when-cross-origin"
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		-Server
	}

	@sse path /api/status/*
	handle @sse {
		reverse_proxy localhost:8310 {
			flush_interval -1
		}
	}

	handle {
		encode zstd gzip
		reverse_proxy localhost:8310
	}
}
